### ISSUE TITLE
Main trends visualization

### ISSUE THREAD

**Issue by bsaul** [nc-minibbs/minibbs.us#23]
Desiderata of the results "landing page" diagram from #22:

* [ ] group species in functional groups
(e.g. grassland, forest birds, etc)
summarize trends within each group in single plot
* [x] ability to filter by county
* [ ] possibly: ability to group into other groupings
such as migratory status
* [ ] tooltip on hover gives more information
possibly: click on a trend line
* [ ] on click reveals plot with trends broken out by species
or some other dimension

**Comment by bsaul** [comment]
@ahhurlbert - I think it was you that suggested showing trends as rates of change, as was done in (I think) the state of the birds report. We could do a simple annual % change, for example. Indeed, such a statistic may be more appealing than simple abundance estimates. Since surveys in each counties started in different year, the total abundance isn't a good overall summary until whatever year (2004?) all three counties were being run.

Thoughts?

**Comment by ahhurlbert** [comment]
If we display abundance, then it should be average abundance per route, and labeled as such. That should take care of the variable number of routes per year. 

We could do % change from baseline, but now I think that will be more difficult to interpret for most users.

**Comment by bsaul** [comment]
It occurs to me that we should have a version where we can toggle between various measures (avg/route, total counts, % change, etc). This version might only be for internal use, and then we can pick one measure for the main display.

**Comment by ahhurlbert** [comment]
Yes, a toggle like that had occurred to me but I didn't want to be too greedy with feature requests at this stage! Good to put on the list though.

**Comment by bsaul** [comment]
> Good to put on the list though.

I added multiple layers (facets) with both totals and avg/route in 638fc29671b099bae47ec1b62dd5d46dba690675. I tried to get a toggle working, but I don't see a way to select position encodings in vega-lite. I'll keep digging.

**Comment by bsaul** [comment]
Here's a screenshot: 

![image](https://user-images.githubusercontent.com/4882990/212706354-837ddf39-8d62-4e3f-b65d-ea7ade072f07.png)

**Comment by bsaul** [comment]
We'll need to account for the skewness of the grouping in whatever measure we chose. For example, `bird.group` in the traits csv is mostly landbird, and a display showing avg count/route measure it's hard to see what's going on with the other groups:

![image](https://user-images.githubusercontent.com/4882990/212710025-e5a68502-e09f-41b7-8e11-63e817b3e3e1.png)
