### ISSUE TITLE
Route "dashboard"

### ISSUE THREAD

**Issue by bsaul** [nc-minibbs/minibbs.us#27]
* display relevant trends and summaries for each route
  * probably have an individual page for each route
  * total abundance by year / number of species per year (in one plot)
  * species table filtered to particular route
  * notable species: species that have only been observed on fewer that # of routes
  * target launch before 2023 survey season

**Comment by bsaul** [comment]
See #22

**Comment by ahhurlbert** [comment]
Other features to include on this page:
* Table with species (listed in taxonomic order) and the % of survey years on which they have been observed on that route
(can add a column or ** designation to highlight species unique to this route, or that occur on fewer than X routes)

* Link to the map page (which should eventually be this page https://www.google.com/maps/d/u/0/viewer?mid=1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0&ll=35.90331302130145%2C-79.1534705&z=10)

* Some way of easily visualizing the date on which survey was conducted each year; could be a separate table, but one option would simply be to add the info to the tool tip hover in the abundance or richness versus year plot, e.g.,

Year: 2005
Date: June 6
Abundance: 255

Thinking through everything that will be helpful to someone taking over a new route

**Comment by bsaul** [comment]
A sketch of dashboard:
[route_dashboard_layout'.pptx](https://github.com/nc-minibbs/minibbs.us/files/12050347/route_dashboard_layout.pptx)

**Comment by bsaul** [comment]
A screenshot of ☝🏼 : 
![image](https://github.com/nc-minibbs/minibbs.us/assets/4882990/106b2eac-51bb-4992-bd76-bc00f58de207)
