### ISSUE TITLE
link to map of survey routes

### ISSUE THREAD

**Issue by caterpillarscountdev** [nc-minibbs/minibbs.us#48]
@IJBG made this GoogleMap with pins for all stops on our survey routes: https://www.google.com/maps/d/u/0/viewer?mid=1NRAImHBzXvdQGpsUzcCPb6tqxUkxMx0&ll=35.87974668820809%2C-78.95706079750232&z=10

Can we link to it in the *Routes* section of this page: https://minibbs.us/procedures.html?

and perhaps on each of the 3 county map pages as well?

@IJBG we should eventually group the pins under their respective routes, each with a different pin color. The distinctive county-route numbers would then show up in the GoogleMaps legend instead of having them all under one umbrella group.

**Comment by bsaul** [comment]
Cool! 

> Can we link to it in the Routes section of this page: https://minibbs.us/procedures.html?  and perhaps on each of the 3 county map pages as well?

Yep, we can do that. I might not get to this until after #47 is done.

**Comment by ahhurlbert** [comment]
@IJBG Based on descriptions of stops from Brian Strong, fix these coordinates:

Chatham Route 10:
Stop 1 (currently missing): 35.665815, -79.096560
Rename Stop 13 as Stop 12 (which is currently missing)
Stop 13 (new): 35.695673, -79.158038

Durham Route 7 descriptions of stops 12-20:
12.         Intersection of 1809 Southview at Church-2.0
13.          510 Southview-0.5
14.          Powerline Crossing-1.0
15.          Past Bridge-1.5
16.          Edge of field-2.0
17.          Kemp and Southview-2.5
18.          Old Kemp Road-0.6
19.          Power line-1.2
20.          Carpenter Pond and Soral Gin-1.7

**Comment by bsaul** [comment]
Closed by #47
